###
GET http://localhost:3001/api

###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "title 1",
  "author": "author 1",
  "url": "url 1"
}

###
DELETE  http://localhost:3001/api/blogs/631e215aed9ce808951162c4
